---
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:edge-alpine
    container_name: actual-budget
    ports:
      - '5006:5006'
    volumes:
      - ./actual-data:/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "actual"
    restart: unless-stopped