---
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      DOMAIN: "https://vaultwarden.${TS_MAGICDNS_SUFFIX:?error}"
      SIGNUPS_ALLOWED: true
    ports:
      - 2708:80
    volumes:
      - ./vaultwarden-data/:/data/
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "vaultwarden"
      tsdproxy.ephemeral: "false"
    networks:
      - tsdproxy
    restart: unless-stopped

networks:
  tsdproxy:
    external: true
