---
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      DOMAIN: "https://vaultwarden.${TS_MAGICDNS_SUFFIX:?error}"
      SIGNUPS_ALLOWED: true
      SSO_ENABLED: true
      SSO_ONLY: true
      SIGNUPS_VERIFY: false
      SSO_SIGNUPS_MATCH_EMAIL: true
      SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: true
      SSO_PKCE: true
      SSO_SCOPES: email profile groups offline_access
    env_file:
      - .env
    ports:
      - 2708:80
    volumes:
      - ./vaultwarden-data/:/data/
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "vaultwarden"
      tsdproxy.ephemeral: "false"
    networks:
      - tsdproxy
    restart: unless-stopped

networks:
  tsdproxy:
    external: true
