---
services:
  timetagger:
    image: ghcr.io/almarklein/timetagger
    ports:
      - "2004:80"
    volumes:
      - ./timetagger-data:/root/_timetagger
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "timetagger"
      tsdproxy.ephemeral: "false"
    networks:
      - tsdproxy
    restart: unless-stopped

networks:
  tsdproxy:
    external: true
