---
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
      - tsdproxydata:/data
      - ./config:/config
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - tsdproxy

volumes:
  tsdproxydata:

networks:
  tsdproxy:
    external: true
